channels:
- conda-forge
dependencies:
- coveralls
- coverage
- bidict =0.22.1
- cloudpickle =3.0.0
- graphviz =8.1.0
- h5io =0.2.2
- matplotlib =3.8.2
- pympipool =0.7.13
- python-graphviz =0.20.1
- toposort =1.10
- typeguard =4.1.5
- ase =3.22.1
- atomistics =0.1.23
- lammps
- phonopy =2.21.0
- pyiron_atomistics =0.4.14
- pyiron-data =0.0.27
- numpy =1.26.4
