channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - graphviz =8.1.0
  - matplotlib =3.8.0
  - numpy =1.26.0
  - pyiron_base =0.6.7
  - pyiron_atomistics =0.3.4
  - toposort =1.10
  - typeguard =4.1.5
