# This runs cron jobs daily

name: Daily

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  codeql:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@tests_in_pythonpath
    secrets: inherit
    with:
      tests-in-python-path: true